// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoAssignmentSimple.Models;

namespace ToDoAssignmentSimple.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20180802152315_removedondeletecascade")]
    partial class removedondeletecascade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoAssignmentSimple.Models.CheckList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CheckListData");

                    b.Property<bool>("ChickListStatus");

                    b.Property<int?>("NoteId");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("CheckList");
                });

            modelBuilder.Entity("ToDoAssignmentSimple.Models.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LabelData");

                    b.Property<int?>("NoteId");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("ToDoAssignmentSimple.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("PinStatus");

                    b.Property<string>("PlainText");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("ToDoAssignmentSimple.Models.CheckList", b =>
                {
                    b.HasOne("ToDoAssignmentSimple.Models.Note")
                        .WithMany("CheckLists")
                        .HasForeignKey("NoteId");
                });

            modelBuilder.Entity("ToDoAssignmentSimple.Models.Label", b =>
                {
                    b.HasOne("ToDoAssignmentSimple.Models.Note")
                        .WithMany("Labels")
                        .HasForeignKey("NoteId");
                });
#pragma warning restore 612, 618
        }
    }
}
